### ISSUE TITLE
Make `tagName` API the official solution for native class components

### ISSUE THREAD

**Issue by mehulkar** [emberjs/rfcs#589] opened 2020-01-29 19:04 UTC
```js
import Component from '@ember/component';

export default Component.extend({
  tagName: ''
});

// vs

export default class FooComponent extends Component {
  tagName = '';
}
```

These look the same and work the same today, but the `tagName` class field in the second example is different from the `tagName` property in the first example. The former is assigned per instance, while the latter goes on the prototype.

There was some chatter in Discord about this not being guaranteed in the future, so an RFC to actually make the `tagName` class field official would be a good idea.

**Comment by pzuraq** [comment] 2020-01-29 19:05
While we're at it, I think we should add a `didCreate` method to classic components that would run at the same time as `init`. This would move us closer to being able to remove classic classes via an optional feature flag.

**Comment by mehulkar** [comment] 2020-01-29 19:06
@pzuraq #588

**Comment by chriskrycho** [comment] 2020-01-30 16:20
Perhaps we could (via *add-on*, not in core!) pull the `@tagName` decorator over from ember-decorators as a default part of the app install but which you can opt out of? Mostly just thinking about how we keep it in line with the rest of the way components normally work.

**Comment by mehulkar** [comment] 2020-01-30 18:59
@chriskrycho what would be in the addon? The issue is to provide a guarantee that `tagName` assigned to the prototype and `tagName` set as a class field both do the same thing as an end result. I don't think that can happen anywhere other than core.

Making this guarantee (it works now, but @pzuraq was concerned that it might not *keep* working) means that the `@tagName` decorator will not be required anymore.

**Comment by chriskrycho** [comment] 2020-01-30 19:40
Ah, I see. Making sure they keep working the same way 👍. Misunderstood what was desired here.

**Comment by Turbo87** [comment] 2020-02-19 08:23
I would very much support this. I don't want to add yet another dependency just to keep the existing `tagName` behavior that actually already works well 👍

**Comment by mehulkar** [comment] 2020-02-19 09:40
Is this really something that needs an RFC? Could this just be moved to an Issue in the core repo? I'm not sure what part of the stack actually reads it off the prototype, but it might even just be a matter of adding it to the public API so that any *changes* go through the RFC process?

**Comment by jherdman** [comment] 2020-02-19 14:27
Do we need the same thing for `layout`?

**Comment by pzuraq** [comment] 2020-02-19 16:24
`layout` is actually a separate issue which was thought through carefully. The problem is that if you assign `layout` directly as a class field, it will run the entire template factory for _every instance_ of the component. This would be very expensive.

Plenty of folks import `layout` and assign it separately, but it's not uncommon to try to define the template factory within the component:

```js
class Foo extends Component {
  layout = hbs`...`;
}
```

> Is this really something that needs an RFC?

I think one reason this may need an RFC is it really represents a shift in policy. The official policy is that Ember does _not_ support native class syntax with classic components as a first class citizen. This was caused by two main reasons:

1. There was uncertainty about the upgrade path. Some believed that it would be better to skip native classes for Classic components altogether, and are pursuing that route. Since components need to be rewritten to convert anyways, this makes some sense.

2. There was not consensus to add other decorators that definitely would be required. At the least, decorators for `@classNameBindings` and `@attributeBindings` would be required to mimic Classic component's behaviors.

This is why there are no official guides for using native classes with Classic components, and why `ember-decorators` still exists as a separate project from Ember.

On the other hand, this is effectively the behavior that already exists, so I think we may be able to say that this behavior (and the behavior of `layout`) will not change without an RFC. I'll bring this up for discussion at the next core team meeting.

**Comment by Turbo87** [comment] 2020-02-19 20:04
> At the least, decorators for @classNameBindings and @attributeBindings would be required to mimic Classic component's behaviors.

I guess that depends on the upgrade path. What I recommend is to refactor to `tagName: ''` first, and at that point you don't need those bindings anymore. Next step is refactoring to a native class, and here `tagName = ''` would be very helpful.

**Comment by pzuraq** [comment] 2020-02-19 20:15
@Turbo87 right, so that would be a third option, and we did discuss this when making that original policy decision. The three migration options are:

1. Convert directly from Classic components to Glimmer components. No intermediate steps. This is the officially supported path (e.g. it's what is documented).

2. Convert to native class syntax for tooling and quality of life benefits, but otherwise treat Classic components the same, and then rewrite to Glimmer components one component at a time. This is the path that the `ember-classic-decorator`, `ember-native-class-codemod`, and `ember-decorators` libraries are meant to support, but is not supported by Ember directly.

3. Convert incrementally feature-by-feature from Classic components to Glimmer components. This is also not supported by Ember directly, except by using classic class syntax.

These changes would make 3 a bit more acceptable, but would not help 2. IMO that's fine, but there were strong reservations from multiple core team members of supporting _anything_ but 1.

**Comment by Turbo87** [comment] 2020-02-19 20:19
IMHO rewriting without intermediate steps is very error-prone and will essentially just cause a lot of apps to never ever migrate. If we essentially force them to do a full rewrite of every component in the app then why not rewrite the app in a different framework directly 😉

**Comment by jherdman** [comment] 2020-02-19 20:26
For what it's worth, at Precision Nutrition we have started migrating using the steps described in this comment https://github.com/emberjs/rfcs/issues/589#issuecomment-588422119, and have been doing so for quite some time. It's definitely made the hop to Glimmer much easier.

**Comment by mehulkar** [comment] 2020-02-19 20:33
Echoing @Turbo87's comments. 

CC to GC rewrites of every component is an opportunity to revisit a LOT more than just Octane (e.g. addons, UI libraries, web components), and it's too burdensome. I chose not to do this or recommend this to any of my teammates. (2) didn't work for me out of box unfortunately. I still believe that (3) is the best approach and worked very well for us. 

So the approach is:

1. angle brackets
1. tagless
1. native classes
1. glimmer components and tracked (if I could, i break this up, but it's not super straightforward)

As such, for steps 2 and 3, we need `tagName = ''` to work.

**Comment by chriskrycho** [comment] 2020-02-19 20:35
The only thing I'd add to the above is that (3) native classes can actually go *first*… modulo concerns about `tagName` and willingness to take on `ember-decorators` as a dependency. We (my team at LinkedIn) have zero discomfort with that, and I personally have been using it for the last two years, and it's *very* solid.

**Comment by wagenet** [comment] 2022-07-23 00:05
I'm closing this due to inactivity. This doesn't mean that the idea presented here is invalid, but that, unfortunately, nobody has taken the effort to spearhead it and bring it to completion. Please feel free to advocate for it if you believe that this is still worth pursuing. Thanks!

**Closed by wagenet** 2022-07-23 00:05 UTC
